mainWorld: world
schematicWorld: flatworld

finished:
  Notch: 50
personal_best:
  Notch: 50

mlgItems:
  - 'WATER_BUCKET:1'
  - 'SLIME_BLOCK:2'
  - 'COBWEB:2'
  - 'OAK_BOAT:1'

# POTION:AMPLIFIER
levelPotionEffects:
  20:
    - 'SLOW:1'
  30:
    - 'BLINDNESS:1'