name: OmniMLG
main: net.omni.mlg.OmniMLGPlugin
version: '1.0'
author: omni
api-version: '1.16'
softdepend:
  - PlaceholderAPI
  - Multiverse-Core
depend:
  - WorldEdit

commands:
  omnimlg:
    usage: /<command>
    description: Main command for OmniMLG.
    aliases:
      - mlg
      - omnim